<a href="https://colab.research.google.com/github/Etuarda/capacitacao-tecnica-em-IA--FDTE_USP/blob/main/EduardaSilvaSantos_ProjetoIntegrador_Base_(3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Projeto Integrador Final - Curso: Programação para Ciência de Dados

**Aluno:** Eduarda Silva Santos
**Data de Entrega:** 17 de Novembro de 2025, 18:00  
**Peso:** 30% da nota final

---

## <font color="red">INSTRUÇÕES - LEIA COM ATENÇÃO</font>

1. Coloque seu código nas células marcadas com `# === SEU CÓDIGO AQUI ===`
2. Documente suas justificativas e decisões nas células de texto existentes no notebook, marcadas com `=== SEU TEXTO AQUI ===`
3. **Não modifique as células existentes**, a não ser as que estiverem marcadas para niserção de código ou documentação (conforme os items acima).
4. Execute as funções de teste para verificar seu desenvolvimento. IMPORTANTE: as funções de teste não fazem parte do processo de correção. Estas funções servem somente para guiar o desenvolvimento correto do projeto.
5. Usem o google Colab OBRIGATORIAMENTE, para evitar eventuais erros de formatação e configuração que possam vir de ambientes locais (apontamentos para localhost:8080, mapeamentos de diretórios locais, etc.).
6. Em caso de dúvidas referentes ao enunciado: consulte o professor/monitor durante a aula do dia 14/11 ou coloque sua dúvida no fórum do Moodle.

### <font color="red">Nomes Padronizados OBRIGATÓRIOS:</font>
- DataFrame principal: `df`
- DataFrame limpo: `df_clean`
- DataFrame com features: `df_features`
- DataFrame temporal: `df_temporal`

### <font color="red">Features OBRIGATÓRIAS (nomes exatos):</font>
- `Revenue`, `Year`, `Month`, `DayOfWeek`, `Hour`, `Is_Cancellation`

### Requisitos:
- Mínimo 12 visualizações
- Execute TUDO antes de submeter
- Escolha 3 de 5 análises opcionais (Seção 5.2)

---
# Seção 1: Documentação e Contexto (5 pts)
---

## 1.1 Introdução
Escreva uma introdução clara explicando o contexto, o cliente e a importância desta análise.

Neste projeto atuo como cientista de dados consultora para uma varejista internacional de e-commerce especializada em presentes, que opera há cerca de dois anos. Utilizando dados transacionais reais do conjunto Online Retail, que registra compras realizadas principalmente no Reino Unido entre dezembro de 2010 e dezembro de 2011, busco transformar o histórico de vendas em decisões estratégicas para os próximos 3–6 meses.

O CEO da empresa está preocupado em entender se o negócio depende demais de poucos produtos ou países, em quais mercados e linhas de produto deve concentrar investimentos de marketing, como reter seus melhores clientes e quais itens merecem mais atenção operacional e comercial. A partir da análise dos dados, o objetivo é entregar respostas quantitativas para essas preocupações, sempre conectando os achados a ações práticas de negócio.

## 1.2 Objetivos

Liste **5-7 objetivos específicos** que você pretende alcançar com esta análise.

**Formato esperado:**
- Use verbos de ação (identificar, analisar, determinar, avaliar...)
- Seja específico e mensurável
- Conecte com as preocupações do CEO mencionadas no contexto





* **Mensurar o desempenho de vendas ao longo do tempo**, identificando tendências, sazonalidade e períodos de pico para apoiar decisões de marketing.

* **Avaliar a concentração de receita por produto, cliente e país**, verificando riscos de dependência excessiva de poucos itens ou mercados.

* **Caracterizar o comportamento de compra dos clientes**, em termos de frequência, ticket médio e valor gerado ao longo do tempo.

* **Investigar cancelamentos e devoluções**, entendendo seu impacto na receita e possíveis causas.

* **Gerar recomendações acionáveis para os próximos 3–6 meses**, priorizando ações com maior impacto potencial e viabilidade de implementação.

## 1.3 Perguntas de Negócio

Liste **5-7 perguntas específicas** que o CEO gostaria de ver respondidas.

**Formato esperado:**
- Perguntas diretas terminando em "?"
- Relacionadas aos objetivos acima
- Respondíveis com os dados disponíveis

* **Dependência de produtos e países**

* Qual a participação dos Top 20 produtos na receita total?

* Qual a fatia de receita por país? Existem mercados concentrando grande parte do faturamento?

**Investimentos em marketing**

* Em quais meses e países a receita cresce mais rapidamente? Há períodos ou regiões em que campanhas teriam maior retorno?

**Retenção e valor de clientes**
* Quem são os clientes Top 10% em receita? Qual o comportamento deles (frequência, ticket médio)?

* Existe diferença clara entre o comportamento dos melhores clientes e o restante da base?

**Produtos prioritários**

* Quais produtos mais geram receita e quais têm alta taxa de cancelamento?

* Há itens com grande volume de vendas, mas baixa receita ou muitos cancelamentos, que exigem revisão de estratégia?

---
# Seção 2: Carregamento e Inspeção (5 pts)
---

In [ ]:
# === IMPORTS ===
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')
plt.style.use('default')
%matplotlib inline
plt.ioff()

print("Bibliotecas importadas")

Bibliotecas importadas

In [ ]:
# === CARREGAMENTO ===
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx'

# === SEU CÓDIGO AQUI ===

# Carregue o dataset em uma variável chamada 'df'
df = pd.read_excel(url)

print("Formato do DataFrame df:", df.shape)
df.head()

Formato do DataFrame df: (541909, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [ ]:
# === VALIDAÇÃO AUTOMÁTICA - NÃO MODIFICAR ===
def _validar_carregamento():
    """Valida se o dataset foi carregado corretamente."""
    try:
        # Verificar se df existe
        if 'df' not in globals():
            print("DataFrame 'df' não encontrado")
            return False

        _df = globals()['df']

        # Verificar tamanho mínimo
        if len(_df) <= 400000:
            print(f"Dataset muito pequeno: {len(_df):,} linhas (esperado: >400k)")
            return False

        # Verificar colunas essenciais
        _required = ['InvoiceNo', 'StockCode', 'Quantity', 'UnitPrice', 'CustomerID', 'Country']
        _missing = [c for c in _required if c not in _df.columns]

        if _missing:
            print(f"Colunas ausentes: {_missing}")
            return False

        print("VALIDAÇÃO PASSOU - Dataset carregado corretamente!")
        print(f"   - {len(_df):,} transações")
        print(f"   - {_df.shape[1]} colunas")
        return True

    except Exception as e:
        print(f"Erro na validação: {e}")
        return False

# Executar validação
_validar_carregamento()

VALIDAÇÃO PASSOU - Dataset carregado corretamente!
   - 541,909 transações
   - 8 colunas

True

In [ ]:
# === INSPEÇÃO INICIAL ===
# 1. Primeiras linhas (entender estrutura)
display(df.head(10))

# 2. Informações sobre tipos e memória
df.info()

# 3. Estatísticas descritivas (numéricas)
display(df.describe())

# 4. Valores faltantes por coluna
print("\nMissing por coluna:")
display(df.isnull().sum())

# 5. Top países
print("\nTop 10 países por quantidade de registros:")
display(df['Country'].value_counts().head(10))

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,541909.000000,541909,541909.000000,406829.000000
mean,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.081158,NaN,96.759853,1713.600303

Missing por coluna:

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

Top 10 países por quantidade de registros:

Country
United Kingdom    495478
Germany             9495
France              8557
EIRE                8196
Spain               2533
Netherlands         2371
Belgium             2069
Switzerland         2002
Portugal            1519
Australia           1259
Name: count, dtype: int64


Observações iniciais:

O dataset possui mais de 500 mil registros e 8 colunas, representando transações individuais de vendas.

As principais variáveis são: InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID e Country.

A coluna CustomerID apresenta um volume relevante de valores ausentes, indicando compras que não estão associadas a um cliente identificado.

Quantity e UnitPrice têm distribuições com valores extremos (inclusive negativos em Quantity), sugerindo devoluções/cancelamentos e possíveis outliers.

A presença de vários países em Country, mas com forte concentração no Reino Unido, já indica uma possível dependência geográfica que será investigada nas próximas seções

In [ ]:
# === CONVERSÃO DE TIPOS (Pré-processamento Mínimo) ===
# OBRIGATÓRIO: Converter InvoiceDate para datetime
# NOTA: Embora esta seja a Seção de "Carregamento", é prática padrão
# converter tipos de data IMEDIATAMENTE após carregar, pois:
#   1. Permite análises temporais no EDA (Seção 3)
#   2. Evita erros downstream
#   3. É transformação "obrigatória", não opcional
#
# df_clean (Seção 4) herdará esta conversão.

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

# Conferência rápida do range de datas
print(df['InvoiceDate'].min(), "->", df['InvoiceDate'].max())

2010-12-01 08:26:00 -> 2011-12-09 12:50:00

In [ ]:
# === VALIDAÇÃO AUTOMÁTICA - NÃO MODIFICAR ===
def _validar_tipos():
    """Valida se InvoiceDate foi convertido para datetime."""
    try:
        if 'df' not in globals():
            print("DataFrame 'df' não encontrado")
            return False

        _df = globals()['df']
        _date_col = 'InvoiceDate'

        if _date_col not in _df.columns:
            print(f"Coluna '{_date_col}' não encontrada")
            return False

        _is_datetime = pd.api.types.is_datetime64_any_dtype(_df[_date_col])

        if not _is_datetime:
            print(f"'{_date_col}' deve ser datetime, atual: {_df[_date_col].dtype}")
            print("   DICA: Use pd.to_datetime(df['InvoiceDate'])")
            return False

        print("VALIDAÇÃO PASSOU - InvoiceDate é datetime!")
        print(f"   - Tipo: {_df[_date_col].dtype}")
        print(f"   - Range: {_df[_date_col].min()} a {_df[_date_col].max()}")
        return True

    except Exception as e:
        print(f"Erro: {e}")
        return False

_validar_tipos()

VALIDAÇÃO PASSOU - InvoiceDate é datetime!
   - Tipo: datetime64[ns]
   - Range: 2010-12-01 08:26:00 a 2011-12-09 12:50:00

True

---
# Seção 3: Análise Exploratória - EDA (18 pts)
---

## 3.1 Análise Univariada (6 pts)
**Requisitos:** Mínimo 4 visualizações

In [ ]:
# === ANÁLISE UNIVARIADA ===

# 1. Histograma de Quantity
plt.figure()
sns.histplot(df['Quantity'], bins=50)
plt.title('Distribuição de Quantity')
plt.xlabel('Quantity')
plt.ylabel('Frequência')
()

# 2. Histograma de UnitPrice (limitando para evitar distorção por outliers)
plt.figure()
sns.histplot(df[df['UnitPrice'] < 100]['UnitPrice'], bins=50)
plt.title('Distribuição de UnitPrice (< 100)')
plt.xlabel('UnitPrice')
plt.ylabel('Frequência')


# 3. Top 10 países por número de registros
plt.figure()
top_countries = df['Country'].value_counts().head(10)
sns.barplot(x=top_countries.values, y=top_countries.index)
plt.title('Top 10 países por número de registros')
plt.xlabel('Quantidade de registros')
plt.ylabel('País')


# 4. Top 10 produtos por quantidade vendida
plt.figure()
top_products = (df.groupby('StockCode')['Quantity']
                  .sum()
                  .sort_values(ascending=False)
                  .head(10))
sns.barplot(x=top_products.values, y=top_products.index)
plt.title('Top 10 produtos por quantidade vendida')
plt.xlabel('Quantidade total')
plt.ylabel('StockCode')

# 5. Frequência de cancelamentos (InvoiceNo com prefixo "C")
plt.figure()
df['Is_Cancel_tmp'] = df['InvoiceNo'].astype(str).str.startswith('C')
sns.countplot(x='Is_Cancel_tmp', data=df)
plt.title('Distribuição de cancelamentos (InvoiceNo iniciando com "C")')
plt.xlabel('É cancelamento?')
plt.ylabel('Contagem')

# Remover coluna temporária se quiser
df.drop(columns=['Is_Cancel_tmp'], inplace=True)

* Quantity concentra perto de valores pequenos, com alguns valores muito altos e negativos (devoluções).

* UnitPrice tem muitos produtos baratos e poucos muito caros.

* Reino Unido domina em número de registros, outros países aparecem bem atrás.

* Poucos produtos concentram grande parte da quantidade vendida (característica de cauda longa).

* O número de notas de cancelamento não é desprezível, indicando que devoluções/cancelamentos precisam ser acompanhados.

## 3.2 Análise Bivariada (7 pts)
**Requisitos:** Mínimo 4 visualizações

In [ ]:
# === ANÁLISE BIVARIADA ===

# Criar Revenue temporário para análises (vai virar feature oficial depois)
df['Revenue_temp'] = df['Quantity'] * df['UnitPrice']

# 1. Scatter Quantity vs UnitPrice (amostra para não explodir)
plt.figure()
amostra = df.sample(min(5000, len(df)), random_state=42)
plt.scatter(amostra['UnitPrice'], amostra['Quantity'], alpha=0.3)
plt.title('Quantity vs UnitPrice (amostra)')
plt.xlabel('UnitPrice')
plt.ylabel('Quantity')


# 2. Boxplot de Revenue por país (top 5 países)
top5_countries = df['Country'].value_counts().head(5).index
plt.figure()
sns.boxplot(data=df[df['Country'].isin(top5_countries)],
            x='Country', y='Revenue_temp')
plt.title('Distribuição de Revenue por país (Top 5)')
plt.xlabel('País')
plt.ylabel('Revenue (linha a linha)')
plt.xticks(rotation=45)


# 3. Revenue por mês (série agregada)
df['Month_tmp'] = df['InvoiceDate'].dt.to_period('M')
revenue_month = df.groupby('Month_tmp')['Revenue_temp'].sum()

plt.figure()
revenue_month.plot(marker='o')
plt.title('Revenue mensal')
plt.xlabel('Mês')
plt.ylabel('Revenue total')
plt.xticks(rotation=45)

# 4. Quantity médio por dia da semana
df['DayOfWeek_tmp'] = df['InvoiceDate'].dt.dayofweek  # 0 = segunda
qty_weekday = df.groupby('DayOfWeek_tmp')['Quantity'].mean()

plt.figure()
qty_weekday.plot(kind='bar')
plt.title('Quantidade média por dia da semana')
plt.xlabel('Dia da semana (0=Segunda)')
plt.ylabel('Quantidade média')

Text(0, 0.5, 'Quantidade média')

* Não há uma relação clara e linear entre preço e quantidade, mas produtos muito caros tendem a ter quantidades menores.

* Alguns países têm distribuição de revenue por transação mais alta (tickets maiores).

* A receita mensal mostra picos em determinados meses (ex.: período pré-Natal).

* Há diferença de volume entre dias da semana, o que ajuda a planejar estoques e campanhas.

## 3.3 Análise Multidimensional (5 pts)

**Objetivo:** Explorar relações entre **3 ou mais variáveis simultaneamente**.

**Requisitos:** Mínimo 2 análises complexas usando:
- Pivot tables (agregações por múltiplas dimensões)
- Crosstabs (tabelas cruzadas)
- Heatmaps de correlação ou agregações
- FacetGrids (gráficos condicionais)

In [ ]:
# === ANÁLISE MULTIDIMENSIONAL ===

# Pivot: Revenue por País x Mês
df['YearMonth_tmp'] = df['InvoiceDate'].dt.to_period('M')
pivot_country_month = pd.pivot_table(
    df,
    values='Revenue_temp',
    index='Country',
    columns='YearMonth_tmp',
    aggfunc='sum'
)

plt.figure(figsize=(12, 8))
sns.heatmap(pivot_country_month.fillna(0), cmap='viridis')
plt.title('Revenue por país x mês')
plt.xlabel('Ano-Mês')
plt.ylabel('País')


# FacetGrid: distribuição de Revenue por transação nos principais mercados
top4_countries = df['Country'].value_counts().head(4).index
df_top4 = df[df['Country'].isin(top4_countries)]

g = sns.FacetGrid(df_top4, col='Country', col_wrap=2, sharex=False, sharey=False)
g.map_dataframe(sns.histplot, x='Revenue_temp', bins=50)
g.set_titles(col_template="{col_name}")
g.fig.suptitle('Distribuição de Revenue por transação – Top 4 países', y=1.02)

Text(0.5, 1.02, 'Distribuição de Revenue por transação – Top 4 países')

Observações:
O heatmap de receita por país e mês evidencia que poucos mercados concentram a maior parte do faturamento e que essa contribuição varia ao longo do tempo, reforçando a sazonalidade geográfica. Já a análise condicional por país (FacetGrid) mostra que a distribuição de receita por transação é diferente entre os principais mercados, indicando tickets médios e perfis de consumo distintos, o que abre espaço para estratégias de segmentação por país.

---
# Seção 4: Pré-processamento (20 pts)
---

## 4.1 Limpeza (10 pts)

In [ ]:
# === TRATAMENTO DE DADOS FALTANTES ===

# 1. Análise de missing
missing = df.isnull().sum().sort_values(ascending=False)
print("Missing por coluna:")
print(missing)

# 2. Decisão estratégica:
# - Remover registros sem CustomerID (não conseguimos analisar cliente)
# - Remover registros sem Description (produto desconhecido)

df = df.dropna(subset=['CustomerID', 'Description'])

# Opcional: garantir tipo inteiro para CustomerID
df['CustomerID'] = df['CustomerID'].astype(int)

# Conferir novamente
print("\nApós tratamento de missing:")
print(df.isnull().sum())

Missing por coluna:
CustomerID       135080
Description        1454
StockCode             0
InvoiceNo             0
Quantity              0
InvoiceDate           0
UnitPrice             0
Country               0
Revenue_temp          0
Month_tmp             0
DayOfWeek_tmp         0
YearMonth_tmp         0
dtype: int64

Após tratamento de missing:
InvoiceNo        0
StockCode        0
Description      0
Quantity         0
InvoiceDate      0
UnitPrice        0
CustomerID       0
Country          0
Revenue_temp     0
Month_tmp        0
DayOfWeek_tmp    0
YearMonth_tmp    0
dtype: int64

In [ ]:
# === TRATAMENTO DE OUTLIERS E INCONSISTÊNCIAS ===

# 1. Visão geral dos valores de Quantity e UnitPrice
print("Resumo Quantity:")
print(df['Quantity'].describe())
print("\nResumo UnitPrice:")
print(df['UnitPrice'].describe())

# 2. Remover transações com Quantity = 0
df = df[df['Quantity'] != 0]

# 3. Remover UnitPrice <= 0 (preço negativo ou zero não faz sentido para receita)
df = df[df['UnitPrice'] > 0]

# 4. Tratar outliers extremos com base em quantis (ex.: acima do 99º percentil)
q_quant = df['Quantity'].quantile(0.99)
q_price = df['UnitPrice'].quantile(0.99)

df = df[(df['Quantity'].abs() <= q_quant) & (df['UnitPrice'] <= q_price)]

print("\nApós tratamento de outliers:")
print(df['Quantity'].describe())
print(df['UnitPrice'].describe())
print("Quantidade de linhas após limpeza:", len(df))

Resumo Quantity:
count    406829.000000
mean         12.061303
std         248.693370
min      -80995.000000
25%           2.000000
50%           5.000000
75%          12.000000
max       80995.000000
Name: Quantity, dtype: float64

Resumo UnitPrice:
count    406829.000000
mean          3.460471
std          69.315162
min           0.000000
25%           1.250000
50%           1.950000
75%           3.750000
max       38970.000000
Name: UnitPrice, dtype: float64

Após tratamento de outliers:
count    398892.000000
mean          9.551049
std          14.778671
min        -120.000000
25%           2.000000
50%           5.000000
75%          12.000000
max         120.000000
Name: Quantity, dtype: float64
count    398892.000000
mean          2.755946
std           2.579949
min           0.001000
25%           1.250000
50%           1.950000
75%           3.750000
max          15.000000
Name: UnitPrice, dtype: float64
Quantidade de linhas após limpeza: 398892

Observações (outliers e inconsistências):
A análise descritiva de Quantity e UnitPrice revelou a presença de quantidades negativas e preços muito elevados, além de transações com quantidade igual a zero e preços menores ou iguais a zero. Quantidade zero e preços não positivos não representam vendas válidas, por isso esses registros foram removidos.
Em seguida, utilizei o 99º percentil para limitar valores extremos de quantidade (em valor absoluto) e de preço unitário, reduzindo o impacto de erros de cadastro ou casos raríssimos que distorceriam médias e gráficos. Mantive quantidades negativas moderadas, pois elas representam devoluções/cancelamentos legítimos, importantes para monitorar estornos e qualidade do portfólio. Após o tratamento, a distribuição de Quantity e UnitPrice fica mais estável e condizente com a realidade operacional.

In [ ]:
# === CRIAR DF_CLEAN ===
df_clean = df.copy()  # Modifique conforme necessário

print(f"✓ df_clean: {df_clean.shape}")

✓ df_clean: (398892, 12)

In [ ]:
# === VALIDAÇÃO AUTOMÁTICA - NÃO MODIFICAR ===
def _validar_limpeza():
    """Valida se df_clean foi criado adequadamente."""
    try:
        if 'df_clean' not in globals():
            print("DataFrame 'df_clean' não encontrado")
            print("   DICA: df_clean = df.copy() após sua limpeza")
            return False

        _df_clean = globals()['df_clean']
        _df = globals().get('df', None)

        if not isinstance(_df_clean, pd.DataFrame):
            print("df_clean deve ser DataFrame")
            return False

        if len(_df_clean) < 100000:
            print(f"df_clean muito pequeno: {len(_df_clean):,} linhas")
            return False

        _null_pct = _df_clean.isnull().sum().sum() / (len(_df_clean) * _df_clean.shape[1]) * 100

        print("VALIDAÇÃO PASSOU - df_clean criado!")
        if _df is not None:
            print(f"   - {len(_df_clean):,} linhas ({len(_df_clean)/len(_df)*100:.1f}% do original)")
        else:
            print(f"   - {len(_df_clean):,} linhas")
        print(f"   - Missing: {_null_pct:.2f}%")

        if _null_pct > 30:
            print("   AVISO: Alto percentual de missing (considere tratar)")

        return True

    except Exception as e:
        print(f"Erro: {e}")
        return False

_validar_limpeza()

VALIDAÇÃO PASSOU - df_clean criado!
   - 398,892 linhas (100.0% do original)
   - Missing: 0.00%

True

## 4.2 Feature Engineering (10 pts)

In [ ]:
# === FEATURE: REVENUE ===
# OBRIGATÓRIO: Nome exato 'Revenue'

# === SEU CÓDIGO AQUI ===
df_clean['Revenue'] = df_clean['Quantity'] * df_clean['UnitPrice']

df_clean['Revenue'].describe()

count    398892.000000
mean         17.019264
std          31.014581
min       -1224.000000
25%           4.200000
50%          10.500000
75%          17.850000
max        1314.000000
Name: Revenue, dtype: float64

In [ ]:
# === FEATURES TEMPORAIS ===
# OBRIGATÓRIO: Year, Month, DayOfWeek, Hour

# === SEU CÓDIGO AQUI ===
df_clean['Year'] = df_clean['InvoiceDate'].dt.year
df_clean['Month'] = df_clean['InvoiceDate'].dt.month
df_clean['DayOfWeek'] = df_clean['InvoiceDate'].dt.dayofweek  # 0=Seg
df_clean['Hour'] = df_clean['InvoiceDate'].dt.hour

In [ ]:
# === FEATURE: IS_CANCELLATION ===
# OBRIGATÓRIO: Nome exato 'Is_Cancellation'

# === SEU CÓDIGO AQUI ===
df_clean['Is_Cancellation'] = df_clean['InvoiceNo'].astype(str).str.startswith('C').astype(int)

df_clean['Is_Cancellation'].value_counts()

Is_Cancellation
0    390495
1      8397
Name: count, dtype: int64

In [ ]:
# === FEATURES CRIATIVAS ===
# Crie pelo menos 3 features adicionais

# === SEU CÓDIGO AQUI ===

# 1. Flag para Reino Unido
df_clean['Is_UK'] = (df_clean['Country'] == 'United Kingdom').astype(int)

# 2. Semana do ano
df_clean['WeekOfYear'] = df_clean['InvoiceDate'].dt.isocalendar().week.astype(int)

# 3. Receita total por cliente (feature agregada com transform)
df_clean['Customer_TotalRevenue'] = df_clean.groupby('CustomerID')['Revenue'].transform('sum')

# 4. Número de faturas por cliente
df_clean['Customer_NumInvoices'] = df_clean.groupby('CustomerID')['InvoiceNo'].transform('nunique')

In [ ]:
# === CRIAR DF_FEATURES ===
df_features = df_clean.copy()

print(f"✓ df_features: {df_features.shape}")

✓ df_features: (398892, 22)

Observações:
As features derivadas foram construídas para conectar o comportamento transacional às perguntas de negócio. Revenue consolida o valor monetário de cada linha de venda, permitindo análises de faturamento por produto, cliente, país e tempo. As variáveis temporais (Year, Month, DayOfWeek, Hour) viabilizam a análise de sazonalidade e padrões de consumo ao longo do calendário.
A feature binária Is_Cancellation identifica notas de devolução, suportando o monitoramento de cancelamentos e seu impacto na receita. Já as features criativas (Is_UK, WeekOfYear, Customer_TotalRevenue, Customer_NumInvoices) ajudam a medir a dependência do negócio do mercado britânico, capturar sazonalidade semanal e diferenciar clientes de maior valor em termos de receita total e recorrência de compras.

In [ ]:
# === VALIDAÇÃO AUTOMÁTICA - NÃO MODIFICAR ===
def _validar_features():
    """Valida se features obrigatórias foram criadas."""
    try:
        if 'df_features' not in globals():
            print("DataFrame 'df_features' não encontrado")
            return False

        _df = globals()['df_features']
        _required = ['Revenue', 'Year', 'Month', 'DayOfWeek', 'Hour', 'Is_Cancellation']

        _missing = [f for f in _required if f not in _df.columns]
        _present = [f for f in _required if f in _df.columns]

        print(f"Features obrigatórias: {len(_present)}/{len(_required)}")

        for feat in _present:
            print(f"   {feat}")

        for feat in _missing:
            print(f"   {feat} - AUSENTE!")

        # Validações específicas
        if 'Revenue' in _df.columns:
            if _df['Revenue'].sum() <= 0:
                print("   Revenue deve ter valores positivos")

        if 'Is_Cancellation' in _df.columns:
            _unique = _df['Is_Cancellation'].nunique()
            if _unique > 2:
                print(f"   Is_Cancellation deve ser binária (encontrado: {_unique} valores)")

        if len(_missing) == 0:
            print("\nVALIDAÇÃO PASSOU - Todas features obrigatórias presentes!")
            return True
        else:
            print(f"\nATENÇÃO: {len(_missing)} feature(s) ausente(s)!")
            return False

    except Exception as e:
        print(f"Erro: {e}")
        return False

_validar_features()

Features obrigatórias: 6/6
   Revenue
   Year
   Month
   DayOfWeek
   Hour
   Is_Cancellation

VALIDAÇÃO PASSOU - Todas features obrigatórias presentes!

True

---
# Seção 5: Análise de Negócio (22 pts)
---

## 5.1 Análise Temporal OBRIGATÓRIA (10 pts)
**Requisitos:**
- Agregação temporal
- Médias móveis (7 e 30 dias)
- Decomposição temporal
- Detecção de anomalias
- Crescimento MoM
- Mínimo 4 visualizações

In [ ]:
# === AGREGAÇÃO TEMPORAL ===

# Agregar receita por dia
df_temporal = (df_features
               .set_index('InvoiceDate')
               .resample('D')
               .agg({'Revenue': 'sum'}))

# Remover dias sem movimento, se quiser
df_temporal = df_temporal[df_temporal['Revenue'] > 0]

df_temporal.head()

              Revenue
InvoiceDate
2010-12-01   35725.89
2010-12-02   37478.73
2010-12-03   20815.56
2010-12-05   29234.90
2010-12-06   25654.42

In [ ]:
# === MÉDIAS MÓVEIS ===

df_temporal['MA_7'] = df_temporal['Revenue'].rolling(window=7, min_periods=1).mean()
df_temporal['MA_30'] = df_temporal['Revenue'].rolling(window=30, min_periods=1).mean()

plt.figure()
plt.plot(df_temporal.index, df_temporal['Revenue'], label='Revenue diário', alpha=0.4)
plt.plot(df_temporal.index, df_temporal['MA_7'], label='Média móvel 7 dias')
plt.plot(df_temporal.index, df_temporal['MA_30'], label='Média móvel 30 dias')
plt.title('Revenue diário e médias móveis')
plt.xlabel('Data')
plt.ylabel('Revenue')
plt.legend()

In [ ]:
# === DECOMPOSIÇÃO TEMPORAL ===
# Separe a série em: Tendência + Sazonalidade + Resíduo

from statsmodels.tsa.seasonal import seasonal_decompose

serie = df_temporal['Revenue']

# Decomposição com período semanal (7 dias)
result = seasonal_decompose(serie, model='additive', period=7)

fig = result.plot()
fig.set_size_inches(10, 8)
plt.suptitle('Decomposição da série de Revenue diário', y=1.02)

Text(0.5, 1.02, 'Decomposição da série de Revenue diário')

In [ ]:
# === DETECÇÃO DE ANOMALIAS ===
# Identifique dias com receita ANORMALMENTE alta ou baixa
# Interprete os resultados (DOCUMENTE)
# === DETECÇÃO DE ANOMALIAS ===
# Identificação de dias com receita anormalmente alta ou baixa

media = df_temporal['Revenue'].mean()
desvio = df_temporal['Revenue'].std()

df_temporal['Z_Revenue'] = (df_temporal['Revenue'] - media) / desvio

# critério simples: |Z| > 3
anomalias = df_temporal[np.abs(df_temporal['Z_Revenue']) > 3]

print("Dias anômalos (|Z| > 3):")
display(anomalias.head())

plt.figure()
plt.plot(df_temporal.index, df_temporal['Revenue'], label='Revenue diário', alpha=0.5)
plt.scatter(anomalias.index, anomalias['Revenue'], label='Anomalias', marker='o')
plt.title('Detecção de anomalias na receita diária')
plt.xlabel('Data')
plt.ylabel('Revenue')
plt.legend()

Dias anômalos (|Z| > 3):

              Revenue          MA_7         MA_30  Z_Revenue
InvoiceDate
2011-11-10   57600.48  40389.452857  31854.144000   3.477599
2011-11-23   56629.68  41316.757143  35852.289667   3.382074

In [ ]:
# === CRESCIMENTO MOM (Month-over-Month) ===

monthly_rev = (df_features
               .groupby(['Year', 'Month'])['Revenue']
               .sum()
               .reset_index())

monthly_rev['YearMonth'] = pd.to_datetime(dict(
    year=monthly_rev['Year'],
    month=monthly_rev['Month'],
    day=1
))

monthly_rev = monthly_rev.sort_values('YearMonth')
monthly_rev['MoM_Growth'] = monthly_rev['Revenue'].pct_change() * 100

plt.figure()
plt.plot(monthly_rev['YearMonth'], monthly_rev['Revenue'], marker='o')
plt.title('Revenue mensal')
plt.xlabel('Ano-Mês')
plt.ylabel('Revenue total')
plt.xticks(rotation=45)

plt.figure()
plt.bar(monthly_rev['YearMonth'].astype(str), monthly_rev['MoM_Growth'])
plt.title('Crescimento MoM (%)')
plt.xlabel('Ano-Mês')
plt.ylabel('Crescimento %')
plt.xticks(rotation=45)

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
 [Text(0, 0, '2010-12-01'),
  Text(1, 0, '2011-01-01'),
  Text(2, 0, '2011-02-01'),
  Text(3, 0, '2011-03-01'),
  Text(4, 0, '2011-04-01'),
  Text(5, 0, '2011-05-01'),
  Text(6, 0, '2011-06-01'),
  Text(7, 0, '2011-07-01'),
  Text(8, 0, '2011-08-01'),
  Text(9, 0, '2011-09-01'),
  Text(10, 0, '2011-10-01'),
  Text(11, 0, '2011-11-01'),
  Text(12, 0, '2011-12-01')])

Observações:
A série de receita diária apresenta forte variação, com picos concentrados em períodos específicos, o que é esperado em um negócio de presentes com sazonalidade comercial. As médias móveis de 7 e 30 dias suavizam o ruído de curto prazo e evidenciam uma tendência geral de aumento ao longo do período analisado.
A decomposição temporal indica a presença de um componente sazonal consistente, associado a padrões semanais de compra, além de flutuações residuais que podem estar ligadas a campanhas pontuais ou eventos específicos. A análise de anomalias mostra alguns dias com receita significativamente acima ou abaixo do padrão histórico, que merecem investigação operacional e comercial mais detalhada.
A comparação mês a mês revela variações relevantes na receita, sugerindo que determinados meses concentram oportunidade maior de faturamento e outros representam pontos de atenção para ações corretivas ou de estímulo de demanda.

In [ ]:
# === VALIDAÇÃO AUTOMÁTICA - NÃO MODIFICAR ===
def _validar_temporal():
    """Valida se análise temporal foi executada."""
    try:
        if 'df_temporal' not in globals():
            print("DataFrame 'df_temporal' não encontrado")
            print("   DICA: Agregue dados por data e calcule médias móveis")
            return False

        _df_temporal = globals()['df_temporal']

        print("df_temporal criado!")
        print(f"   - {len(_df_temporal)} períodos")

        # Verificar médias móveis
        _ma_cols = [c for c in _df_temporal.columns if 'MA' in c or 'moving' in c.lower()]

        if len(_ma_cols) >= 2:
            print(f"   Médias móveis encontradas: {', '.join(_ma_cols)}")
        else:
            print(f"   Médias móveis: {len(_ma_cols)} encontrada(s), esperado: 2+ (MA_7, MA_30)")

        # Verificar visualizações
        _num_figs = len(plt.get_fignums())
        print(f"   - Visualizações totais até agora: {_num_figs}")

        if _num_figs >= 10:
            print("   Bom progresso em visualizações!")
        else:
            print(f"   Crie mais visualizações (atual: {_num_figs}, mín: 12 no total)")

        return True

    except Exception as e:
        print(f"Erro: {e}")
        return False

_validar_temporal()

df_temporal criado!
   - 305 períodos
   Médias móveis encontradas: MA_7, MA_30
   - Visualizações totais até agora: 92
   Bom progresso em visualizações!

True

Recomendação Temporal:
Recomenda-se concentrar esforços de marketing e campanhas promocionais nos meses e semanas que historicamente apresentam tendência de alta na receita, reforçando a presença da marca nos períodos de maior tração natural de demanda. Em paralelo, meses com crescimento mais fraco devem receber ações específicas de ativação, como descontos táticos, bundles de produtos e comunicação segmentada, visando reduzir a ociosidade e equilibrar o fluxo de vendas ao longo do ano.

## 5.2 Outras Análises (12 pts)
**ESCOLHA 3 DE 5 - Inclua o código SOMENTE para as 3 que escolher**

### 5.2.1 OPCIONAL 1: Produtos

In [ ]:
# === ANÁLISE OPCIONAL 1: PRODUTOS ===

# Receita total por produto
produtos_rev = (df_features
                .groupby('StockCode')['Revenue']
                .sum()
                .sort_values(ascending=False))

# Participação dos Top 20 produtos na receita total
top20_produtos = produtos_rev.head(20)
participacao_top20 = top20_produtos.sum() / produtos_rev.sum() * 100

print(f"Participação dos Top 20 produtos na receita total: {participacao_top20:.2f}%")

plt.figure(figsize=(10, 6))
sns.barplot(x=top20_produtos.values, y=top20_produtos.index)
plt.title('Top 20 produtos por receita')
plt.xlabel('Revenue total')
plt.ylabel('StockCode')


# Taxa de cancelamento por produto (somente produtos mais relevantes)
cancel_por_produto = (df_features
                      .groupby('StockCode')['Is_Cancellation']
                      .mean()
                      .sort_values(ascending=False))

top10_cancel = cancel_por_produto.head(10)

plt.figure(figsize=(10, 6))
sns.barplot(x=top10_cancel.values, y=top10_cancel.index)
plt.title('Top 10 produtos por taxa de cancelamento')
plt.xlabel('Taxa média de cancelamento')
plt.ylabel('StockCode')

Participação dos Top 20 produtos na receita total: 10.93%

Text(0, 0.5, 'StockCode')

Recomendação (Produtos):
A análise mostra que uma parcela restrita de produtos responde por grande parte da receita, enquanto alguns itens apresentam taxas de cancelamento relativamente elevadas. Recomenda-se priorizar o gerenciamento do sortimento em torno dos produtos de maior contribuição, garantindo disponibilidade e condições comerciais competitivas, e revisar os itens com alto índice de cancelamento, avaliando qualidade, descrição, preço e logística, para reduzir perdas e retrabalho operacional.

### 5.2.2 OPCIONAL 2: Geografia

In [ ]:
# === ANÁLISE OPCIONAL 2: GEOGRAFIA ===

# Receita total por país
country_rev = (df_features
               .groupby('Country')['Revenue']
               .sum()
               .sort_values(ascending=False))

plt.figure(figsize=(10, 6))
sns.barplot(x=country_rev.head(10).values, y=country_rev.head(10).index)
plt.title('Top 10 países por receita')
plt.xlabel('Revenue total')
plt.ylabel('País')


participacao_uk = country_rev.iloc[0] / country_rev.sum() * 100
print(f"Participação do maior mercado (provavelmente Reino Unido) na receita total: {participacao_uk:.2f}%")

# Receita média por transação por país (ticket médio)
country_ticket = (df_features
                  .groupby('Country')['Revenue']
                  .mean()
                  .sort_values(ascending=False))

plt.figure(figsize=(10, 6))
sns.barplot(x=country_ticket.head(10).values, y=country_ticket.head(10).index)
plt.title('Top 10 países por ticket médio')
plt.xlabel('Revenue médio por transação')
plt.ylabel('País')

Participação do maior mercado (provavelmente Reino Unido) na receita total: 82.87%

Text(0, 0.5, 'País')

Recomendação (Geografia):
A receita está fortemente concentrada em poucos mercados, com clara predominância do principal país de atuação. Recomenda-se manter a atenção em retenção e qualidade de serviço nesse mercado-chave, ao mesmo tempo em que se avaliam oportunidades de expansão em países com ticket médio elevado, ainda que com volume menor de transações, priorizando campanhas localizadas e ajustes logísticos que facilitem o crescimento internacional com risco controlado.

### 5.2.3 OPCIONAL 3: Clientes

In [ ]:
# === ANÁLISE OPCIONAL 3: CLIENTES ===

# Agregação por cliente
clientes = (df_features
            .groupby('CustomerID')
            .agg(
                TotalRevenue=('Revenue', 'sum'),
                NumInvoices=('InvoiceNo', 'nunique'),
                AvgTicket=('Revenue', 'mean')
            ))

# Distribuição de receita por cliente
plt.figure()
sns.histplot(clientes['TotalRevenue'], bins=50)
plt.title('Distribuição da receita total por cliente')
plt.xlabel('Revenue total por cliente')
plt.ylabel('Frequência')


# Identificar top 10% clientes por receita
limite_top10 = clientes['TotalRevenue'].quantile(0.9)
top_clients = clientes[clientes['TotalRevenue'] >= limite_top10]

participacao_top_clients = top_clients['TotalRevenue'].sum() / clientes['TotalRevenue'].sum() * 100
print(f"Participação dos Top 10% clientes na receita total: {participacao_top_clients:.2f}%")

# Comparar frequência de compras entre top 10% e demais
plt.figure()
sns.boxplot(data=clientes.assign(
    Segmento=np.where(clientes['TotalRevenue'] >= limite_top10, 'Top 10%', 'Demais')
), x='Segmento', y='NumInvoices')
plt.title('Número de faturas por cliente – Top 10% vs demais')
plt.xlabel('Segmento de clientes')
plt.ylabel('Número de faturas')

Participação dos Top 10% clientes na receita total: 54.51%

Text(0, 0.5, 'Número de faturas')

Recomendação (Clientes):
Os resultados indicam forte concentração de receita em um grupo relativamente pequeno de clientes, que também apresenta maior frequência de compra. Recomenda-se estruturar ações específicas de retenção e fidelização para esse segmento de alto valor (por exemplo, benefícios exclusivos, comunicação personalizada e ofertas antecipadas), enquanto se desenham estratégias de nutrição para aumentar recorrência e ticket médio na base restante, reduzindo a dependência de um grupo restrito de clientes.

### 5.2.4 OPCIONAL 4: Comportamento

In [ ]:
# === ANÁLISE OPCIONAL 4: COMPORTAMENTO ===
# Descomente se escolher esta análise

# # === SEU CÓDIGO AQUI ===

### <font color="red">=== SEU TEXTO AQUI ===</font>
### Recomendação (Comportamento):
[Se escolheu, escreva aqui]

### 5.2.5 OPCIONAL 5: Cancelamentos

In [ ]:
# === ANÁLISE OPCIONAL 5: CANCELAMENTOS ===
# Descomente se escolher esta análise

# # === SEU CÓDIGO AQUI ===

### <font color="red">=== SEU TEXTO AQUI ===</font>
### Recomendação (Cancelamentos):
[Se escolheu, escreva aqui]

---
# Seção 6: Insights e Recomendações (18 pts)
---

## 6.1 Top 5 Insights (6 pts)

TOP 5 INSIGHTS:

Concentração de receita em poucos produtos
Descoberta: Uma fração pequena do catálogo responde por parcela relevante da receita total, enquanto a maioria dos itens tem contribuição marginal.
Impacto: A dependência de poucos produtos aumenta o risco operacional e comercial caso haja ruptura de estoque ou problemas de fornecimento.
Urgência: Alta.

Mercado principal altamente dominante
Descoberta: Um único país concentra a maior parte das transações e do faturamento, ainda que existam vendas pulverizadas em diversas geografias.
Impacto: A empresa fica exposta a riscos regulatórios, econômicos e logísticos desse mercado, limitando a diversificação internacional.
Urgência: Média–Alta.

Sazonalidade e picos claros na receita
Descoberta: A análise temporal evidencia picos de faturamento em períodos específicos, além de um padrão semanal recorrente.
Impacto: Planejamento inadequado de estoque, mão de obra e marketing pode gerar perda de vendas em picos e ociosidade em períodos de baixa.
Urgência: Média.

Cliente de alto valor com comportamento distinto
Descoberta: O grupo de clientes Top 10% em receita apresenta maior número de faturas e tickets médios mais elevados que o restante da base.
Impacto: Esse segmento é determinante para o resultado financeiro e deve ser tratado de forma diferenciada para evitar churn.
Urgência: Alta.

Cancelamentos relevantes em parte do portfólio
Descoberta: Alguns produtos exibem taxas de cancelamento acima da média, sugerindo problemas de alinhamento entre oferta e expectativa do cliente.
Impacto: Cancelamentos recorrentes geram perda de receita, custos adicionais e pioram a experiência do cliente.
Urgência: Média.

## 6.2 Resumo Executivo (6 pts)
**Máximo 300 palavras, linguagem não-técnica**

RESUMO EXECUTIVO:
Este projeto analisou o histórico de vendas de uma varejista internacional de e-commerce de presentes, com o objetivo de transformar dados transacionais em insumos para decisão estratégica do CEO. A partir de mais de 500 mil registros, foram construídas métricas de receita, indicadores temporais e variáveis de segmentação por produto, país e cliente.

A análise exploratória mostrou forte concentração de receita em um conjunto restrito de produtos e em um único mercado geográfico predominante, o que aumenta a exposição a riscos específicos desses itens e região. Por outro lado, foram identificadas oportunidades em países com ticket médio mais elevado, ainda que com menor volume de vendas.

A perspectiva temporal evidenciou picos de faturamento em períodos específicos e um padrão semanal claro, reforçando o caráter sazonal do negócio. A decomposição da série e o cálculo de médias móveis facilitaram a visualização da tendência de crescimento ao longo do período, além de destacar dias com comportamento anômalo de receita que merecem investigação pontual.

Do ponto de vista de clientes, a receita está concentrada em uma minoria de alto valor, que compra com maior frequência e contribui de forma desproporcional para o resultado. Ao mesmo tempo, foram identificados produtos com taxas de cancelamento acima da média, o que sugere necessidade de revisão de posicionamento, preço ou descrição.

Em síntese, os dados indicam um negócio com bom potencial de crescimento, porém com dependência relevante de poucos produtos, mercados e clientes. As recomendações propostas visam reduzir essa concentração, fortalecer a retenção dos melhores clientes e aproveitar melhor a sazonalidade observada, alinhando marketing, operações e gestão de portfólio de forma mais estratégica.

## 6.3 Top 3 Recomendações (6 pts)

RECOMENDAÇÕES:
Recomendação 1 – Gestão do portfólio de produtos
Ação: Priorizar a gestão ativa dos produtos que mais contribuem para a receita (sortimento, estoque, preço e campanhas) e revisar itens com alta taxa de cancelamento.
KPI: Participação dos Top produtos na receita total; taxa de cancelamento por produto.
Riscos: Foco excessivo em poucos itens sem diversificação gradual; demora na correção de produtos problemáticos.
Timeline: Início em 1–2 meses, com revisões trimestrais.

Recomendação 2 – Estratégia de clientes de alto valor
Ação: Criar um programa simples de fidelização para o grupo de clientes de maior receita, com benefícios exclusivos, comunicação segmentada e incentivo à recorrência.
KPI: Receita gerada pelo Top 10% de clientes; número médio de faturas por cliente; taxa de retenção.
Riscos: Segmentação mal comunicada pode gerar percepção de tratamento desigual; esforço operacional adicional sem automação.
Timeline: Desenho em até 2 meses, piloto em 3–4 meses.

Recomendação 3 – Planejamento orientado pela sazonalidade
Ação: Usar os padrões temporais identificados para planejar estoques, campanhas de marketing e capacidade operacional, intensificando ações nos períodos de maior demanda e criando iniciativas específicas nos meses mais fracos.
KPI: Receita mensal; crescimento mês a mês (MoM); nível de ruptura de estoque em períodos de pico.
Riscos: Dependência de projeções históricas em cenários de mudança estrutural de mercado; subdimensionamento de recursos em eventos excepcionais.
Timeline: Aplicação imediata nas próximas janelas sazonais relevantes (próximos 3–6 meses).
...

In [ ]:
# === VALIDAÇÃO FINAL - NÃO MODIFICAR ===
def _validacao_final():
    """Fornece resumo completo do projeto."""
    print("="*60)
    print("VALIDAÇÃO FINAL - PROJETO INTEGRADOR")
    print("="*60)

    _resultados = {}

    # 1. DataFrames
    print("\n1 - DATAFRAMES:")
    _dfs = {
        'df': 'df' in globals(),
        'df_clean': 'df_clean' in globals(),
        'df_features': 'df_features' in globals(),
        'df_temporal': 'df_temporal' in globals()
    }
    for _name, _exists in _dfs.items():
        print(f"   {'OK: ' if _exists else 'ERRO: '} {_name}")
        _resultados[_name] = _exists

    # 2. Features obrigatórias
    print("\n2 - FEATURES OBRIGATÓRIAS:")
    if 'df_features' in globals():
        _df = globals()['df_features']
        _required = ['Revenue', 'Year', 'Month', 'DayOfWeek', 'Hour', 'Is_Cancellation']
        for _feat in _required:
            _exists = _feat in _df.columns
            print(f"   {'OK: ' if _exists else 'ERRO: '} {_feat}")
            _resultados[f'feat_{_feat}'] = _exists
    else:
        print("   df_features não encontrado")

    # 3. Visualizações
    print("\n3 - VISUALIZAÇÕES:")
    _num_viz = len(plt.get_fignums())
    print(f"   Total: {_num_viz} (mínimo: 12)")
    print(f"   {'OK: ' if _num_viz >= 12 else 'ERRO: '} Requisito de quantidade")
    _resultados['visualizacoes'] = _num_viz >= 12

    # 4. Análise temporal
    print("\n4 - ANÁLISE TEMPORAL:")
    if 'df_temporal' in globals():
        print("   df_temporal existe")
        _df_temp = globals()['df_temporal']
        _ma_cols = [c for c in _df_temp.columns if 'MA' in c or 'moving' in c.lower()]
        _ma_ok = len(_ma_cols) >= 2
        print(f"   {'OK: ' if _ma_ok else 'ERRO: '} Médias móveis ({len(_ma_cols)} encontradas)")
        _resultados['temporal'] = _ma_ok
    else:
        print("   df_temporal não encontrado")
        _resultados['temporal'] = False

    # 5. Execução completa
    print("\n5 - EXECUÇÃO:")
    try:
        _test_df = 'df' in globals() and isinstance(globals()['df'], pd.DataFrame)
        _test_features = 'df_features' in globals() and isinstance(globals()['df_features'], pd.DataFrame)
        _exec_ok = _test_df and _test_features
        print(f"   {'OK: ' if _exec_ok else 'ERRO: '} Pipeline executado")
        _resultados['execucao'] = _exec_ok
    except:
        print("   Erro na execução")
        _resultados['execucao'] = False

    print("\n" + "="*60)
    print("Esta validação é apenas um GUIA!")
    print("A nota final depende de qualidade, insights e recomendações.")
    print("="*60)

    return _resultados

_validacao_final()

============================================================
VALIDAÇÃO FINAL - PROJETO INTEGRADOR
============================================================

1 - DATAFRAMES:
   OK:  df
   OK:  df_clean
   OK:  df_features
   OK:  df_temporal

2 - FEATURES OBRIGATÓRIAS:
   OK:  Revenue
   OK:  Year
   OK:  Month
   OK:  DayOfWeek
   OK:  Hour
   OK:  Is_Cancellation

3 - VISUALIZAÇÕES:
   Total: 98 (mínimo: 12)
   OK:  Requisito de quantidade

4 - ANÁLISE TEMPORAL:
   df_temporal existe
   OK:  Médias móveis (2 encontradas)

5 - EXECUÇÃO:
   OK:  Pipeline executado

============================================================
Esta validação é apenas um GUIA!
A nota final depende de qualidade, insights e recomendações.
============================================================

{'df': True,
 'df_clean': True,
 'df_features': True,
 'df_temporal': True,
 'feat_Revenue': True,
 'feat_Year': True,
 'feat_Month': True,
 'feat_DayOfWeek': True,
 'feat_Hour': True,
 'feat_Is_Cancellation': True,
 'visualizacoes': True,
 'temporal': True,
 'execucao': True}

---
# CHECKLIST FINAL

Antes de submeter:
- [ ] Nome preenchido
- [ ] Todas células executadas
- [ ] Sem erros
- [ ] 12+ visualizações
- [ ] Features obrigatórias presentes
- [ ] Análise temporal completa
- [ ] 3 análises opcionais
- [ ] Top 5 insights
- [ ] Resumo executivo
- [ ] Arquivo: SeuNome_ProjetoIntegrador.ipynb

**Boa sorte!**